### ISSUE TITLE
API USER STORY: Create Event

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/events-backend-api#10]
As a **developer/superuser** I can **create a new event** so that **this event will be displayed in the events list**

## Acceptance Criteria:

* Acceptance Criteria 1: Event form contains all model fields
* Acceptance Criteria 2: Saved event displayed in event list view
* Acceptance Criteria 3:

## Tasks:

- [ ] Create Python code - Add serializer
- [ ] Create MVC code - Add createview method
- [ ] Test completed functionality
