### ISSUE TITLE
API USER STORY: Edit comment

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/events-backend-api#13]
As a **developer/superuser** I can **edit a comment that I created** so that **I can amend any missing or incorrect information**

## Acceptance Criteria:

* Acceptance Criteria 1: Edit button is only available to owner of comment - is_owner = true
* Acceptance Criteria 2: Create edit event form to amend event model fields
* Acceptance Criteria 3: New or edited data saved back to the original comment id

## Tasks:

- [ ] Create Python code - Create edit comment serializer form. Permissions classes - Is Owner or ReadOnly
- [ ] Create MVC code - Add Update View to the views.py
- [ ] Test completed functionality - test the output in the browser.
