### ISSUE TITLE
API USER STORY: Delete Comment

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/events-backend-api#14]
As a **developer/superuser** I can **delete a comment which I created** so that **I can delete comment data from the API**

## Acceptance Criteria:

* Acceptance Criteria 1: Delete button is only available to owner of comment - is_owner = true
* Acceptance Criteria 2: Delete button removes comment from the comment list view
* Acceptance Criteria 3: Must be logged in to view delete button

## Tasks:

- [ ] Create Python code - Create delete button
- [ ] Create MVC code - Add delete View to the views.py
- [ ] Test completed functionality - test the output in the browser.
