### ISSUE TITLE
API USER STORY: Profile Detail

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/events-backend-api#2]
As a **developer/superuser** I can **capability** so that **received benefit**

## Acceptance Criteria:

* Acceptance Criteria 1:
* Acceptance Criteria 2:
* Acceptance Criteria 3:

## Tasks:

- [ ] Create Python code
- [ ] Create MVC code
- [ ] Test completed functionality
