### ISSUE TITLE
API USER STORY: Create going instance

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/events-backend-api#20]
As a **developer/superuser** I can **interested object linked to a single event** so that I can **show interest in an event**

## Acceptance Criteria:

* Acceptance Criteria 1: Required Fields: Owner, event, created_at
* Acceptance Criteria 2: To be ordered with most recently created first
* Acceptance Criteria 3:  Add Unique_together method so that you can only mark 'going' to an event once.

## Tasks:

- [ ] Create Python code - Add model fields, and serializer
- [ ] Create MVC code - Add create view and url path
- [ ] Test completed functionality - check admin panel for correct output
