### ISSUE TITLE
API USER STORY: Delete Going

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/events-backend-api#21]
As a **developer/superuser** I can **delete a going object which I created** so that **I can delete going data from the API**

## Acceptance Criteria:

* Acceptance Criteria 1: Delete button is only available to owner of going - is_owner = true
* Acceptance Criteria 2: Delete button removes going from the list view
* Acceptance Criteria 3: Must be logged in to view delete button

## Tasks:

- [ ] Create Python code - Create delete button
- [ ] Create MVC code - Add destroy View to the views.py
- [ ] Test completed functionality - test the output in the browser.
