### ISSUE TITLE
API USER STORY: Create follow

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/events-backend-api#22]
As a **developer/superuser** I can **create a follow** so that I can **follow another user**

## Acceptance Criteria:

* Acceptance Criteria 1: Follow model includes: owner(following), followed, created_at
* Acceptance Criteria 2: When follow instance is created, user gets a following instance id
* Acceptance Criteria 3: When follow instance is created, selected profile to follow gets a followed instance id
* Acceptance Criteria 4: User is unable to follow a single profile twice
* Acceptance Criteria 5: User must be logged in to create a follow 

## Tasks:

- [ ] Create Python code - Model, Serializer
- [ ] Create MVC code - ListCreate view
- [ ] Test completed functionality
