### ISSUE TITLE
API USER STORY: Edit Profile

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/events-backend-api#3]
As a **developer/superuser** I can **edit a profile when I am logged in** so that **update my personal information**

## Acceptance Criteria:

* Acceptance Criteria 1: Edit button is only available to owner of profile - is_owner = true
* Acceptance Criteria 2: Create edit profile form to add optional data fields to the profille not created on User creation through signals
* Acceptance Criteria 3: New or edited data saved back to the original profile id

## Tasks:

- [ ] Create Python code - Create edit profile form
- [ ] Create MVC code - Add Update View to the views.py
- [ ] Test completed functionality - test the output in the browser.
