### ISSUE TITLE
API USER STORY: View counts

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/events-backend-api#31]
As a **developer/superuser** I can **view sortable fields** so that **I can easily see the field counts**

## Acceptance Criteria:

* Acceptance Criteria 1: View total events_count in the events list
* Acceptance Criteria 2: View followers_count in the profile list
* Acceptance Criteria 3: View following_count in the profile list
* Acceptance Criteria 4: View Comments count in the events list
* Acceptance Criteria 5: View interested_count in the events list
* Acceptance Criteria 6: View going_count in the events list
* Acceptance Criteria 7: View reviews count in the reviews list
* Acceptance Criteria 8: View ratings count in the reviews list

## Tasks:

- [ ] Create Python code - Annotate queryset for each count
- [ ] Create MVC code -  Add the annotate method to the correct serializer
- [ ] Test completed functionality
