### ISSUE TITLE
API USER STORY: View events counts

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/events-backend-api#33]
As a **developer/superuser** I can **view sortable fields** so that **I can easily see the field counts when viewing an event**

## Acceptance Criteria:

* Acceptance Criteria 1: View comments_count in the event list and detail view
* Acceptance Criteria 2: View interested_count in the event list and detail view
* Acceptance Criteria 3: View going_count in the event list and detail view
* Acceptance Criteria 4: view reviews_count in the event list and detail view

## Tasks:

- [ ] Create Python code - Add fields to the serializer
- [ ] Create MVC code -  Add the annotate method to the both list and detail views
- [ ] Test completed functionality
