### ISSUE TITLE
API USER STORY: View review counts

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/events-backend-api#34]
As a **developer/superuser** I can **view sortable fields** so that **I can easily see the field counts when viewing a review**

## Acceptance Criteria:

* Acceptance Criteria 1: View reviews_count in the event list and detail view
* Acceptance Criteria 2: View average ratings in the event list and detail view

## Tasks:

- [ ] Create Python code - Add fields to the serializer
- [ ] Create MVC code -  Add the annotate method to the both list and detail views
- [ ] Test completed functionality

**Comment by quiltingcode** [comment]
I have decided this feature is not necessary as it duplicates what is on the events view.
