### ISSUE TITLE
API USER STORY: Delete Profile

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/events-backend-api#4]
As a **developer/superuser** I can **delete a profile that I own** so that **I can delete my user account from the API**

## Acceptance Criteria:

* Acceptance Criteria 1: Delete button is only available to owner of profile - is_owner = true
* Acceptance Criteria 2: Delete button removes profile from the profile list view
* Acceptance Criteria 3: Deleted profile no longer accessible in detail view

## Tasks:

- [ ] Create Python code - Create delete profile button
- [ ] Create MVC code - Add delete View to the views.py
- [ ] Test completed functionality - test the output in the browser.
