### ISSUE TITLE
API USER STORY: Edit event

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/events-backend-api#7]
As a **developer/superuser** I can **edit an event that I created** so that **I can amend any missing or incorrect information on the event posting**

## Acceptance Criteria:

* Acceptance Criteria 1: Edit button is only available to owner of event - is_owner = true
* Acceptance Criteria 2: Create edit event form to amend event model fields
* Acceptance Criteria 3: New or edited data saved back to the original event id

## Tasks:

- [ ] Create Python code - Create edit event form
- [ ] Create MVC code - Add Update View to the views.py
- [ ] Test completed functionality - test the output in the browser.
