### ISSUE TITLE
API USER STORY: Delete Event

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/events-backend-api#8]
As a **developer/superuser** I can **delete an event which I created** so that **I can delete event data from the API**

## Acceptance Criteria:

* Acceptance Criteria 1: Delete button is only available to owner of profile - is_owner = true
* Acceptance Criteria 2: Delete button removes event from the event list view
* Acceptance Criteria 3: Deleted event no longer accessible in detail view

## Tasks:

- [ ] Create Python code - Create delete button
- [ ] Create MVC code - Add delete View to the views.py
- [ ] Test completed functionality - test the output in the browser.
