### ISSUE TITLE
API USER STORY: Permissions

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/events-backend-api#9]
As a **developer/superuser** I can **login/out** so that **I can access edit and delete functions for data that I created**

## Acceptance Criteria:

* Acceptance Criteria 1: Login/out dropdown option in browser
* Acceptance Criteria 2: When logged in, edit and delete options available for data that the logged in user created
* Acceptance Criteria 3: When logged out, list and detail view available

## Tasks:

- [ ] Create Python code - Add permissions.py to the project
- [ ] Create MVC code - Add permissions_classes to the views edit and delete methods
- [ ] Test completed functionality

**Comment by quiltingcode** [comment]
Edit and Delete event have permissions set to block logged out users, and logged in users who are not the owner of the event

**Comment by quiltingcode** [comment]
Permissions added to comments app to stop logged out users from creating new comments. Once logged in, only users who own the comment can edit or delete them.

**Comment by quiltingcode** [comment]
Add permissions to interested and going to add read only for logged out and not owners, and delete permission for instance owner

**Comment by quiltingcode** [comment]
Add permissions to followers to only allow logged in users who created the follow to delete it
